import os
import base64
import json

# The folder containing the manually trimmed .ogg files
INPUT_DIR = "edited"
# The TypeScript file that will be generated
OUTPUT_TS_FILE = "audioData.ts"

# This defines the structure and which filenames belong to which category.
# This MUST match the filenames saved in the 'edited' folder.
FILE_STRUCTURE = {
    "MOMOI_BASE64": [
        "kuyashi.ogg",
        "tasukete.ogg",
        "yurusenai.ogg",
    ],
    "EXTRA_KEYWORD_BASE64": {
        "reisa": "reisa.ogg",
        "nozomi": "nozomi.ogg",
        "hikari": "hikari.ogg",
        "aoba": "aoba.ogg",
        "miyu": "miyu.ogg",
        "aris": "aris.ogg",
        "kei": "kei.ogg",
        "erika": "erika.ogg",
        "izuna": "izuna.ogg",
        "kanoe": "kanoe.ogg",
        "atsuko": "atsuko.ogg",
        "shiroko": "shiroko.ogg",
        "moyai": "moyai.ogg",
        "koyuki": [f"koyuki_{i}.ogg" for i in range(1, 10)],
        "aru": [f"aru_{i}.ogg" for i in range(1, 3)],
        "mika": [f"mika_{i}.ogg" for i in range(1, 4)],
        "arona": [f"arona_{i}.ogg" for i in range(1, 3)],
        "yuuka": [f"yuuka_{i}.ogg" for i in range(1, 4)],
        "koharu": [f"koharu_{i}.ogg" for i in range(1, 3)],
        "otogi": [f"otogi_{i}.ogg" for i in range(1, 3)],
    }
}

def encode_file_to_base64(filepath):
    """Reads a file and returns its Base64 encoded string."""
    try:
        with open(filepath, 'rb') as f:
            return base64.b64encode(f.read()).decode('utf-8')
    except FileNotFoundError:
        print(f"  WARNING: File not found: {filepath}. It will be omitted.")
        return None

if __name__ == "__main__":
    if not os.path.isdir(INPUT_DIR):
        print(f"ERROR: Input directory '{INPUT_DIR}/' not found. Please create it and add your edited audio files.")
    else:
        print(f"Reading edited audio files from '{INPUT_DIR}/'...")
        
        # Build the data dictionaries
        momoi_data = {}
        for filename in FILE_STRUCTURE["MOMOI_BASE64"]:
            key = filename.split('.')[0]
            filepath = os.path.join(INPUT_DIR, filename)
            encoded_data = encode_file_to_base64(filepath)
            if encoded_data:
                momoi_data[key] = encoded_data

        extra_data = {}
        for key, value in FILE_STRUCTURE["EXTRA_KEYWORD_BASE64"].items():
            if isinstance(value, str): # Single file
                filepath = os.path.join(INPUT_DIR, value)
                encoded_data = encode_file_to_base64(filepath)
                if encoded_data:
                    extra_data[key] = encoded_data
            elif isinstance(value, list): # List of files (koyuki)
                extra_data[key] = []
                for filename in value:
                    filepath = os.path.join(INPUT_DIR, filename)
                    encoded_data = encode_file_to_base64(filepath)
                    if encoded_data:
                        extra_data[key].append(encoded_data)

        # Generate the TypeScript file content
        ts_content = f"""// This file is auto-generated by a script. Do not edit manually.

export const MOMOI_BASE64: Record<string, string> = {json.dumps(momoi_data, indent=4)};

export const EXTRA_KEYWORD_BASE64: Record<string, string | string[]> = {json.dumps(extra_data, indent=4)};
"""

        # Write the content to the .ts file
        with open(OUTPUT_TS_FILE, 'w', encoding='utf-8') as f:
            f.write(ts_content)
        
        print(f"\nSuccessfully generated '{OUTPUT_TS_FILE}'. You can now use this in your plugin.")
